Name: DropzoneJS
Articles:
    - Title: How to build a file upload form using DropzoneJS and Go
      Source: https://medium.com/hackernoon/how-to-build-a-file-upload-form-using-dropzonejs-and-go-8fb9f258a991
      Author: https://twitter.com/@kataras
    - Title: How to display existing files on server using DropzoneJS and Go
      Source: https://medium.com/@kataras/how-to-display-existing-files-on-server-using-dropzonejs-and-go-53e24b57ba19
      Author: https://twitter.com/@kataras